name: Hello!

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: say hello
        run: echo "Hello!!!"

      - name: list files
        run: ls -ilah *
